(#153) - Autogenerated Module Readme updated to included Module Name and Version
puppetlabs/Puppet.Dsc pull request #163
Opened 2021-06-02 10:40 UTC by david22swan

2021-06-02 17:01 UTC, michaeltlombardi requested changes
Could you also add a changelog entry to this (should get an entry in the `Fixed` section) and update the commit to be something like:

```
(GH-153) Ensure generated readme contains module name info

This commit corrects a bug where the auto-generated readme
was missing the PowerShell and Puppet module names from
various locations in the output markdown.

Those values were not being passed by New-PuppetDscModule
to Update-PuppetModuleReadme.

This commit also updates tests to ensure the values are passed.

Resolves #153
```

The changelog entry should match the format of the other entries (linking to the issue) and have a message like:

> Ensure puppetized module READMEs include the PowerShell and Puppet module names where needed in the markdown.

2021-06-03 17:18 UTC, michaeltlombardi requested changes
Minor request for changelog entry modifications.

(non-blocking): If this PR could be broken into three commits (one for each modified function), that would be preferable.

2021-06-03 17:18 UTC, michaeltlombardi commented on CHANGELOG.md
> +- With the exception of `PuppetModuleName` all `Update-PuppetModuleReadme` parameters have been set to mandatory and to not except null or empty values. `PuppetModuleName` has been left as when not g
```suggestion
- Make all `Update-PuppetModuleReadme` parameters except `PuppetModuleName` mandatory and do not accept null or empty values ([#153](https://github.com/puppetlabs/Puppet.Dsc/issues/153))
```

2021-06-03 17:18 UTC, michaeltlombardi commented on CHANGELOG.md
> +- Have ensured that the auto generated readme contains both the PowerShell and Puppet module names ([#153](https://github.com/puppetlabs/Puppet.Dsc/issues/153))
```suggestion
- Ensure that the auto-generated readme of a Puppetized module contains both the PowerShell and Puppet module names ([#153](https://github.com/puppetlabs/Puppet.Dsc/issues/153))
```

2021-06-03 17:18 UTC, michaeltlombardi commented on CHANGELOG.md
> +- For `Get-Readmecontent` the parameters for `PowerShellModuleName` and `PuppetModuleName` have both been set to mandatory and all values have been set to not accept null or empty values ([#153](http
```suggestion
- Make the  `PowerShellModuleName` and `PuppetModuleName` parameters in `Get-Readmecontent` mandatory and do not accept null or empty values for any parameters ([#153](https://github.com/puppetlabs/Puppet.Dsc/issues/153))
```

2021-06-03 17:41 UTC, david22swan commented
Have updated the changelog and split the commit into 3 commits

2021-06-04 12:00 UTC, michaeltlombardi approved these changes

2021-06-04 12:00 UTC, merged